### ISSUE TITLE
Update readme to meet community plugin style guidelines

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-check-log#5]
Style guide is published here: https://github.com/sensu-plugins/community/blob/master/PLUGIN_STYLEGUIDE.md

Specifically, this readme would be more useful with an example check configuration. Here's one where I've captured sensu-backend logs into /tmp and I'm checking them for `error`:

```
type: CheckConfig
api_version: core/v2
metadata:
  name: tmp-backend-log
spec:
  check_hooks: null
  command: sensu-check-log -match error -state /tmp/backend.log.state -log /tmp/backend.log
  interval: 10
  publish: true
  runtime_assets:
  - sensu-check-log
  stdin: true
  subscriptions:
  - backend
  timeout: 10
```

It would be my preference to include an example which will be more immediately applicable to a wide cross section of users, but in most cases the standard log files on a Linux system are not readable by non-root users.
